kind: pipeline
name: snowsync
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:

- name: make
  pull: if-not-exists
  image: golang:1.24.4
  commands:
  - apt update && apt install -y zip
  - mkdir bin
  - make
  - ls -lah bin/

- name: sonar-scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner:v4.5
